Report config name for missing config values.
Previously, when a "required" config value was missing, the config
object's variable name was reported, rather than the name actually used
in the builder.conf file itself.

This resulted in the following output, for example:
ERROR: Missing required field in config file: ServerStateDir
rather than
ERROR: Missing required field in config file: SERVER_STATE_DIR

This patch falls back to the variable name if a config field does not
have a "toml" name defined.

Signed-off-by: Kevin C. Wells <kevin.c.wells@intel.com>